# Generated by Django 2.1.3 on 2018-11-02 17:27

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import logomachy.utils.moderator_mixin
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='The date this record was lat updated.')),
                ('name', models.SlugField(help_text='The simple and unique name of this document. A combination of creator name and document title is recommended.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='The title of this document.', max_length=300, unique=True)),
                ('description', models.TextField(blank=True, help_text='A summary of the content of this document.', max_length=1000, null=True)),
                ('category', models.CharField(choices=[('law', 'Law'), ('tos', 'Terms of Service'), ('eula', 'End User License Agreement'), ('privacy', 'Privacy Policy')], help_text='The category of this document.', max_length=50)),
                ('created_user', models.ForeignKey(blank=True, help_text='The user that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_document_created', related_query_name='logomachy_document_creators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
            bases=(models.Model, logomachy.utils.moderator_mixin.ModeratorMixin),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='The date this record was lat updated.')),
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A generated, unique name for a result.', unique=True)),
                ('processor_name', models.SlugField(help_text='The unique name of the processor that output this result.', max_length=200, unique=True)),
                ('processor_version', models.CharField(help_text='The version of the processor.', max_length=100)),
                ('processor_type', models.CharField(choices=[('source', 'Source'), ('parse', 'Parse'), ('interpret', 'Interpret'), ('analyse', 'Analyse')], help_text='The type of processor.', max_length=100)),
                ('started_date', models.DateTimeField(help_text='The date the processing started.')),
                ('output', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='The output from the processor.')),
                ('created_user', models.ForeignKey(blank=True, help_text='The user that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_result_created', related_query_name='logomachy_result_creators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='The date this record was lat updated.')),
                ('name', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A generated, unique name for a revision.', unique=True)),
                ('language', models.CharField(help_text='The language of this revision of the document.', max_length=10)),
                ('country', models.CharField(help_text='The country locale of this revision of the document.', max_length=10)),
                ('source_url', models.URLField(blank=True, help_text='Link to a website where the latest document can be obtained.', max_length=2000, null=True)),
                ('source_value', models.CharField(choices=[('file', 'File'), ('url', 'URL'), ('url', 'String')], help_text='The source of this revision of the document.', max_length=2000)),
                ('source_media_type', models.CharField(blank=True, help_text='The source media type of this revision of the document.', max_length=100, null=True)),
                ('creator_url', models.URLField(blank=True, help_text='Link to a website of the creator of this revision of the document.', max_length=2000, null=True)),
                ('content_raw', models.TextField(help_text='Raw content of this revision of the document.')),
                ('content_normalised', models.TextField(blank=True, help_text='Normalised content of this revision of the document.', null=True)),
                ('created_user', models.ForeignKey(blank=True, help_text='The user that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_revision_created', related_query_name='logomachy_revision_creators', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='This revision is a version of this document.', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='logomachy.Document')),
                ('updated_user', models.ForeignKey(blank=True, help_text='The user that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_revision_updated', related_query_name='logomachy_revision_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revision',
                'verbose_name_plural': 'Revisions',
            },
            bases=(models.Model, logomachy.utils.moderator_mixin.ModeratorMixin),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='The date this record was created.')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='The date this record was lat updated.')),
                ('name', models.SlugField(help_text='The simple name of this tag.', max_length=100, unique=True)),
                ('title', models.CharField(help_text='A verbose name for this tag.', max_length=700)),
                ('description', models.TextField(blank=True, help_text='A description of this tag.', null=True)),
                ('created_user', models.ForeignKey(blank=True, help_text='The user that created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_tag_created', related_query_name='logomachy_tag_creators', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, help_text='The user that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_tag_updated', related_query_name='logomachy_tag_updaters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='result',
            name='revisions',
            field=models.ManyToManyField(help_text='The revisions used as input to the processor.', related_name='results', to='logomachy.Revision'),
        ),
        migrations.AddField(
            model_name='result',
            name='updated_user',
            field=models.ForeignKey(blank=True, help_text='The user that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_result_updated', related_query_name='logomachy_result_updaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(help_text='The tags applied to this revision of a document, for example indicating a geographic or social region, author or creator, or application scope.', related_name='documents', to='logomachy.Tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_user',
            field=models.ForeignKey(blank=True, help_text='The user that last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logomachy_document_updated', related_query_name='logomachy_document_updaters', to=settings.AUTH_USER_MODEL),
        ),
    ]
